FROM ubuntu:20.04

# Sneak the stf executable into $PATH.
ENV PATH /app/bin:$PATH

# Work in app dir by default.
WORKDIR /app

# Export default app port, not enough for all processes but it should do
# for now.
EXPOSE 3000

# Install app requirements. Trying to optimize push speed for dependant apps
# by reducing layers as much as possible. Note that one of the final steps
# installs development files for node-gyp so that npm install won't have to
# wait for them on the first native module installation.
RUN export DEBIAN_FRONTEND=noninteractive && \
    useradd --system --create-home --shell /usr/sbin/nologin stf-build && \
    useradd --system --create-home --shell /usr/sbin/nologin stf && \
    sed -i'' 's@http://archive.ubuntu.com/ubuntu/@mirror://mirrors.ubuntu.com/mirrors.txt@' /etc/apt/sources.list && \
    apt-get update && \
    apt-get -y install wget python3 build-essential && \
    cd /tmp && \
    wget --progress=dot:mega https://nodejs.org/dist/v17.9.0/node-v17.9.0-linux-x64.tar.xz && \
    tar -xJf node-v*.tar.xz --strip-components 1 -C /usr/local && \
    rm node-v*.tar.xz && \
    su stf-build -s /bin/bash -c '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js install' && \
    apt-get -y install libzmq3-dev libprotobuf-dev git graphicsmagick openjdk-8-jdk yasm cmake && \
    apt-get clean && \
    rm -rf /var/cache/apt/* /var/lib/apt/lists/*

# Just copy package.json and package-lock.json
COPY ./package*.json /tmp/build/

# Give permissions to our build user.
RUN mkdir -p /app && \
    chown -R stf-build:stf-build /tmp/build /app

# Switch over to the build user.
USER stf-build

# Install just the package dependencies before copying in the full source
RUN set -x && \
    cd /tmp/build && \
    npm install --loglevel http

# Just copy bower.json
COPY --chown=stf-build:stf-build ./bower.json /tmp/build/

# Bower install
RUN set -x && \
    cd /tmp/build && \
    export PATH=$PWD/node_modules/.bin:$PATH && \
    bower install && \
    bower cache clean

# Copy the rest of the app source in
COPY --chown=stf-build:stf-build . /tmp/build/

# Run the build.
RUN set -x && \
    cd /tmp/build && \
    npm pack && \
    tar xzf devicefarmer-stf-*.tgz --strip-components 1 -C /app && \
    npm prune --production && \
    mv node_modules /app && \
    npm cache clean --force && \
    rm -rf ~/.node-gyp && \
    cd /app && \
    find /tmp -mindepth 1 ! -regex '^/tmp/hsperfdata_root\(/.*\)?' -delete

# Switch to the app user.
USER stf

# Show help by default.
CMD stf --help
